config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :friendships, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :users, except: [:new]
  resources :posts
  resources :comments, only: [:new, :create, :edit, :destroy, :update]

  get 'users/new', to: 'devise/registrations#new'
  get 'friends/', to: 'friendships#friends'
  post 'friendships/:id', to: 'friendships#update'
  get 'friends/requests', to: 'friendships#index'

  get 'privacy_policy', to: 'static_pages#index'

  root to: 'posts#index'

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_facebook_user_session
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :commenter, class_name: 'User'

  validates :content, presence: true, length: { minimum: 20 }

  def self.all_latest
    all.order(created_at: :desc)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
  end

  def create
    @commenter = current_user
    @comment = @commenter.comments.build(comment_params)
    post = Post.find(params[:comment][:post_id])

    if @comment.save
      flash[:success] = 'Comment successfully added'
      redirect_to post_path(post)
    else
      flash[:error] = 'Error saving comment :-('
      redirect_to request.referer
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    return false unless @comment&.commenter == current_user

    if @comment&.destroy
      flash[:success] = 'Comment successfully deleted'
    else
      flash[:error] = 'Error deleting comment :-('
    end
    redirect_to request.referer
  end

  def edit; end

  def update; end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def delete_comment(comment)
    return if comment.commenter != current_user

    link_to 'delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }
  end
end

app/views/comments/_comment.html.erb
<p>
  <small><%= "#{comment.commenter.first_name}  #{comment.commenter.last_name}" %></small>
  <br>
  <%= comment.content %>
  <p>
  <%= delete_comment(comment) %>
  <p>
</p>

app/views/comments/_form.html.erb
<%= form_for :comment, url: comments_path  do |f|%>
  <%= f.hidden_field :post_id, value: post.id  %>
  <%= f.label :content %>
  <%= f.text_area (:content) %>

  <div>
  <%= f.submit 'send comment' %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>