config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :friendships, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :users, except: [:new]
  resources :posts
  resources :comments, only: [:new, :create, :edit, :destroy, :update]

  get 'users/new', to: 'devise/registrations#new'
  get 'friends/', to: 'friendships#friends'
  post 'friendships/:id', to: 'friendships#update'
  get 'friends/requests', to: 'friendships#index'

  get 'privacy_policy', to: 'static_pages#index'

  root to: 'posts#index'

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_facebook_user_session
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friendship.rb
# frozen_string_literal: true

class Friendship < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  validate :friendship_exists?, :no_self_love

  def friendship_exists?
    if Friendship.find_by('sender_id = ? AND receiver_id = ?',
                          sender_id, receiver_id)
      errors.add(:repeate_relation, 'Friendship relation already exists')
    end
  end

  def no_self_love
    errors.add(:repeate_relation, 'You can\'t friend your self silly') if sender_id == receiver_id
  end

  def self.between(user1, user2)
    Friendship.find_by('(sender_id = ? AND receiver_id = ?) OR (sender_id = ? AND receiver_id = ?)',
                       user1.id, user2.id, user2.id, user1.id)
  end
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  protect_from_forgery prepend: true
  after_action :create_mutal_friend, only: [:update]

  def create
    friendship = Friendship.new(friendship_params)

    if friendship.save
      flash[:success] = 'Friend request sent!'
    else
      flash[:error] = 'Error sending friend request'
    end
    redirect_to request.referer
  end

  def destroy
    friendship = Friendship.find(params[:id])

    return false unless friendship&.receiver == current_user

    if friendship&.destroy
      flash[:success] = 'You are no longer friends...'
    else
      flash[:error] = 'Sorry, but bffs forever'
    end
    redirect_to request.referer
  end

  def update
    friendship = Friendship.find(params[:id])

    return false unless friendship&.receiver == current_user

    if friendship&.update_attribute('status', params[:friendship][:status])
      if params[:friendship][:status] == true
        flash[:success] = 'You are now friends!'
      elsif params[:friendship][:status] == false
        flash[:success] = 'User blocked succesfully...'
      end
    else
      flash[:error] = 'Error updating friend status'
      return false
    end
    redirect_to request.referer
  end

  def index
    @requests = current_user.received_requests
  end

  def friends
    @friends = current_user.friends
  end

  private

  def create_mutal_friend
    if Friendship.create(sender_id: params[:friendship][:receiver_id],
                         receiver_id: params[:friendship][:sender_id], status: params[:friendship][:status])
      flash[:success] = 'You are now mutual friends!'
    else
      flash[:error] = 'Error updating friend status'
    end
  end

  def friendship_params
    params.require(:friendship).permit(:sender_id, :receiver_id)
  end
end

app/helpers/friendships_helper.rb
# frozen_string_literal: true

module FriendshipsHelper
end

app/views/friendships/_friendship.html.erb
<%= form_for :friendship, url: friendships_path do |f| %>
<%= f.hidden_field :sender_id, value: current_user.id %>
<%= f.hidden_field :receiver_id, value: user.id %>
<%= f.submit 'Friend User' %>
<% end %>

app/views/friendships/_requests.html.erb
<% requests.each  do |request| %>
  <%= user_gravatar request.sender %>
  <%= "#{request.sender.first_name} #{request.sender.first_name} wants to be your friend" %>
  <%= form_for :friendship, method: :put, url: friendship_path(request.id) do |f| %>
    <%= f.hidden_field :sender_id, value: request.sender.id %>
    <%= f.hidden_field :receiver_id, value: request.receiver.id %>
    <%= f.hidden_field :status, value: true %>
    <%= f.submit 'Accept friendship' %>
  <% end %>
<% end %>

app/views/friendships/friends.html.erb
<h1>Friends List</h1>
<main id='friends-list'>
  <%= render partial: 'users/user', collection: @friends, as: :user %>
</main>

app/views/friendships/index.html.erb
<h1>Friendship requests</h1>
<main id='request-list'>
  <%= render 'friendships/requests', requests: @requests %>
</main>